<?php

namespace Database\Seeders;

use App\Models\Permission;
use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{
    public function run()
    {

        $i = 1;
        $permissions = [
            [
                'id' => $i++,
                'title' => 'user_management_access',
                'type' => 'role.user.audit_log',
                'parent' => 1,
            ],
            [
                'id' => $i++,
                'title' => 'permission_create',
                'type' => 'permission',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'permission_edit',
                'type' => 'permission',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'permission_show',
                'type' => 'permission',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'permission_delete',
                'type' => 'permission',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'permission_access',
                'type' => 'permission',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'role_create',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'role_edit',
                'type' => 'role',
                'parent' => 0,

            ],
            [
                'id' => $i++,
                'title' => 'role_show',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'role_delete',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'role_access',
                'type' => 'role',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'user_create',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'user_edit',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'user_show',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'user_delete',
                'type' => 'user',
                'parent' => 0,

            ],
            [
                'id' => $i++,
                'title' => 'user_access',
                'type' => 'user',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'setting_edit',
                'type' => 'setting',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'setting_access',
                'type' => 'setting',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'slider_create',
                'type' => 'slider',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'slider_edit',
                'type' => 'slider',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'slider_show',
                'type' => 'slider',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'slider_delete',
                'type' => 'slider',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'slider_access',
                'type' => 'slider',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'about_association_access',
                'type' => 'about',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'service_create',
                'type' => 'service',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'service_edit',
                'type' => 'service',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'service_show',
                'type' => 'service',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'service_delete',
                'type' => 'service',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'service_access',
                'type' => 'service',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'frontend_setting_access',
                'type' => 'slider.partner.service.team',
                'parent' => 1,
            ],
            [
                'id' => $i++,
                'title' => 'project_create',
                'type' => 'project',
                'parent' => 2,
            ],
            [
                'id' => $i++,
                'title' => 'project_edit',
                'type' => 'project',
                'parent' => 2,
            ],
            [
                'id' => $i++,
                'title' => 'project_show',
                'type' => 'project',
                'parent' => 2,
            ],
            [
                'id' => $i++,
                'title' => 'project_delete',
                'type' => 'project',
                'parent' => 2,
            ],
            [
                'id' => $i++,
                'title' => 'project_access',
                'type' => 'project',
                'parent' => 2,
            ],
            [
                'id' => $i++,
                'title' => 'beneficiary_create',
                'type' => 'beneficiary',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'beneficiary_edit',
                'type' => 'beneficiary',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'beneficiary_show',
                'type' => 'beneficiary',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'beneficiary_delete',
                'type' => 'beneficiary',
                'parent' => 2,
            ],
            [
                'id' => $i++,
                'title' => 'beneficiary_access',
                'type' => 'beneficiary',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'media_center_access',
                'type' => 'news.articles.gallery',
                'parent' => 1,

            ],
            [
                'id' => $i++,
                'title' => 'news_create',
                'type' => 'news',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'news_edit',
                'type' => 'news',
                'parent' => 0,

            ],
            [
                'id' => $i++,
                'title' => 'news_show',
                'type' => 'news',
                'parent' => 0, 
            ],
            [
                'id' => $i++,
                'title' => 'news_delete',
                'type' => 'news',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'news_access',
                'type' => 'news',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'said_about_us_create',
                'type' => 'said_about_us',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'said_about_us_edit',
                'type' => 'said_about_us',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'said_about_us_show',
                'type' => 'said_about_us',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'said_about_us_delete',
                'type' => 'said_about_us',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'said_about_us_access',
                'type' => 'said_about_us',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'partner_create',
                'type' => 'partner',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'partner_edit',
                'type' => 'partner',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'partner_show',
                'type' => 'partner',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'partner_delete',
                'type' => 'partner',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'partner_access',
                'type' => 'partner',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'hawkma_mangment_access',
                'type' => 'hawkam_category.hawkma',
                'parent' => 1,
            ],
            [
                'id' => $i++,
                'title' => 'hawkam_category_create',
                'type' => 'hawkam_category',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'hawkam_category_edit',
                'type' => 'hawkam_category',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'hawkam_category_show',
                'type' => 'hawkam_category',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'hawkam_category_delete',
                'type' => 'hawkam_category',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'hawkam_category_access',
                'type' => 'hawkam_category',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'hawkma_create',
                'type' => 'hawkma',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'hawkma_edit',
                'type' => 'hawkma',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'hawkma_show',
                'type' => 'hawkma',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'hawkma_delete',
                'type' => 'hawkma',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'hawkma_access',
                'type' => 'hawkma',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'report_mangment_access',
                'type' => 'report_category.report.report_money',
                'parent' => 1,
            ],
            [
                'id' => $i++,
                'title' => 'report_category_create',
                'type' => 'report_category',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'report_category_edit',
                'type' => 'report_category',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'report_category_show',
                'type' => 'report_category',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'report_category_delete',
                'type' => 'report_category',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'report_category_access',
                'type' => 'report_category',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'report_create',
                'type' => 'report',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'report_edit',
                'type' => 'report',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'report_show',
                'type' => 'report',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'report_delete',
                'type' => 'report',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'report_access',
                'type' => 'report',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'report_money_create',
                'type' => 'report_money',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'report_money_edit',
                'type' => 'report_money',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'report_money_show',
                'type' => 'report_money',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'report_money_delete',
                'type' => 'report_money',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'report_money_access',
                'type' => 'report_money',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'gallery_create',
                'type' => 'gallery',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'gallery_edit',
                'type' => 'gallery',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'gallery_show',
                'type' => 'gallery',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'gallery_delete',
                'type' => 'gallery',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'gallery_access',
                'type' => 'gallery',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'volunteering_managment_access',
                'type' => 'volunteer.volunteer_guide.volunteer_task',
                'parent' => 1,
            ],
            [
                'id' => $i++,
                'title' => 'volunteer_create',
                'type' => 'volunteer',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'volunteer_edit',
                'type' => 'volunteer',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'volunteer_show',
                'type' => 'volunteer',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'volunteer_delete',
                'type' => 'volunteer',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'volunteer_access',
                'type' => 'volunteer',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'volunteer_guide_create',
                'type' => 'volunteer_guide',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'volunteer_guide_edit',
                'type' => 'volunteer_guide',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'volunteer_guide_show',
                'type' => 'volunteer_guide',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'volunteer_guide_delete',
                'type' => 'volunteer_guide',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'volunteer_guide_access',
                'type' => 'volunteer_guide',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'membership_access',
                'type' => 'membership',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'membership_type_create',
                'type' => 'membership',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'membership_type_edit',
                'type' => 'membership',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'membership_type_show',
                'type' => 'membership',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'membership_type_delete',
                'type' => 'membership',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'membership_type_access',
                'type' => 'membership',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'member_create',
                'type' => 'member',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'member_edit',
                'type' => 'member',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'member_show',
                'type' => 'member',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'member_delete',
                'type' => 'member',
                'parent' => 0,
            ],

            [
                'id' => $i++,
                'title' => 'member_access',
                'type' => 'member',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'contact_mangment_access',
                'type' => 'contact.subscribe',
                'parent' => 1,
            ],


            [
                'id' => $i++,
                'title' => 'subscribe_create',
                'type' => 'subscribe',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'subscribe_edit',
                'type' => 'subscribe',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'subscribe_show',
                'type' => 'subscribe',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'subscribe_delete',
                'type' => 'subscribe',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'subscribe_access',
                'type' => 'subscribe',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'director_create',
                'type' => 'director',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'director_edit',
                'type' => 'director',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'director_show',
                'type' => 'director',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'director_delete',
                'type' => 'director',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'director_access',
                'type' => 'director',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'support_create',
                'type' => 'support',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'support_edit',
                'type' => 'support',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'support_show',
                'type' => 'support',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'support_delete',
                'type' => 'support',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'support_access',
                'type' => 'support',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'certificate_create',
                'type' => 'certificate',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'certificate_edit',
                'type' => 'certificate',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'certificate_show',
                'type' => 'certificate',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'certificate_delete',
                'type' => 'certificate',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'certificate_access',
                'type' => 'certificate',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'article_create',
                'type' => 'articles',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'article_edit',
                'type' => 'articles',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'article_show',
                'type' => 'articles',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'article_delete',
                'type' => 'articles',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'article_access',
                'type' => 'articles',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'team_create',
                'type' => 'team',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'team_edit',
                'type' => 'team',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'team_show',
                'type' => 'team',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'team_delete',
                'type' => 'team',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'team_access',
                'type' => 'team',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'profile_password_edit',
                'type' => 'profile_password',
                'parent' => 2,
            ],
            // Video Category Permissions
            [
                'id' => $i++,
                'title' => 'video_category_access',
                'type' => 'video_category',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'video_category_create',
                'type' => 'video_category',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'video_category_edit',
                'type' => 'video_category',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'video_category_show',
                'type' => 'video_category',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'video_category_delete',
                'type' => 'video_category',
                'parent' => 0,
            ],
            // Video Permissions
            [
                'id' => $i++,
                'title' => 'video_access',
                'type' => 'video',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'video_create',
                'type' => 'video',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'video_edit',
                'type' => 'video',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'video_show',
                'type' => 'video',
                'parent' => 0,
            ],
            [
                'id' => $i++,
                'title' => 'video_delete',
                'type' => 'video',
                'parent' => 0,
            ],
        ];

        Permission::insert($permissions);
    }
}
